### ISSUE TITLE
attr thickness conflicts with appcompat v7:21.+ (with fix)

### ISSUE THREAD

**Issue by prazjain** [arcadefire/circled-picker#5]
Hi Mate,
I thought I let you know about this.
I got into this issue and after hours of cursing and pulling my hair off, this is the solution I have found.

Adding references to new appcompat v7:21.+ in gradle will fail the build, if someone is using your project.
Error looks something like this:
attr "thickness" has already been defined.

There is no way to find what was wrong, this link helped me : http://stackoverflow.com/questions/26480624/appcompat-v721-0-0-not-working-with-google-play-service-6-1

Solution: 
I renamed your "thickness" attribute with "outerThickness" (or anything but "thickness")
and also renamed the same in code like below:
mThickness = typedArray.getDimensionPixelSize(R.styleable.CircledPicker_outerThickness,
                (int) MeasureUtils.convertDpToPixel(context, 5));

Hope this helps others using your library.

**Comment by arcadefire** [comment]
Hello there,
thank you for reporting this, I fix that name in the last commit, replacing with outerThickness as suggested. :)
